export const ru = {
  brand: "Aurum Hotels",
  brandTag: "Бронирование отелей",
  skipLink: "Перейти к основному содержимому",
  nav: {
    home: "Главная",
    hotels: "Каталог",
    profile: "Личный кабинет",
  },
  footer: {
    tagline: "Бронирование отелей по всему миру",
  },
  auth: {
    loginTitle: "Вход в аккаунт",
    loginSubtitle: "Войдите, чтобы бронировать отели и управлять заказами",
    registerTitle: "Регистрация",
    registerSubtitle: "Создайте аккаунт за минуту — бронирование только для авторизованных",
    email: "Email",
    password: "Пароль",
    confirmPassword: "Повторите пароль",
    name: "Имя",
    loginBtn: "Войти",
    registerBtn: "Регистрация",
    logout: "Выйти",
    loading: "Загрузка…",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    registerLink: "Зарегистрироваться",
    loginLink: "Войти",
    passwordMismatch: "Пароли не совпадают",
  },
  home: {
    title: "Отели по всему миру — бронь в один клик",
    subtitle:
      "Россия, Европа, Азия и Ближний Восток. Поиск по стране и городу, фильтры и онлайн-бронирование.",
    cta: "Смотреть каталог",
    popularTitle: "Популярные отели",
  },
  filters: {
    title: "Фильтры",
    country: "Страна",
    allCountries: "Все страны",
    city: "Город",
    allCities: "Все города",
    stars: "Звёздность",
    anyStars: "Любая",
    minRating: "Мин. рейтинг",
    anyRating: "Любой",
    sort: "Сортировка",
    sortRatingDesc: "Рейтинг ↓",
    sortRatingAsc: "Рейтинг ↑",
    sortPriceAsc: "Цена ↑",
    sortPriceDesc: "Цена ↓",
    sortStarsDesc: "Звёзды ↓",
    sortCityAsc: "Город А–Я",
    apply: "Применить фильтры",
    reset: "Сбросить",
    found: "Найдено",
  },
  hotels: {
    title: "Каталог отелей",
    subtitle:
      "Выберите страну и город или воспользуйтесь поиском по названию отеля.",
    search: "Поиск",
    searchPlaceholder: "Название отеля…",
    city: "Город",
    cityPlaceholder: "Москва, Анталья…",
    minPrice: "Цена от, ₽",
    maxPrice: "Цена до, ₽",
    submit: "Найти",
    recent: "Недавние запросы:",
    perNight: " / ночь",
    details: "Забронировать",
    rating: "Рейтинг",
    loading: "Загрузка отелей…",
    empty: "По вашему запросу отелей не найдено. Измените фильтры.",
    apiError: "Не удалось загрузить отели. Запустите API: npm run dev",
  },
  hotel: {
    loading: "Загрузка отеля…",
    notFound: "Отель не найден",
    back: "← Назад к каталогу",
    perNight: "за ночь",
    category: "категория",
    amenities: "Удобства",
    bookTitle: "Бронирование номера",
    bookHint: "Данные сохраняются в базе и привязаны к вашему аккаунту.",
    loginRequired: "Войдите или зарегистрируйтесь, чтобы забронировать номер.",
    guestName: "ФИО гостя",
    email: "Электронная почта",
    checkIn: "Дата заезда",
    checkOut: "Дата выезда",
    guests: "Количество гостей",
    submit: "Подтвердить бронь",
    submitting: "Оформление…",
    errName: "Укажите имя",
    errEmail: "Укажите корректный email",
    errCheckIn: "Укажите дату заезда",
    errCheckOut: "Укажите дату выезда",
    errDates: "Дата выезда должна быть позже заезда",
  },
  profile: {
    title: "Личный кабинет",
    subtitle: "Управляйте бронями и сохраняйте понравившиеся отели.",
    tabBookings: "Мои брони",
    tabFavorites: "Избранное",
    statsBookings: "броней",
    statsFavorites: "в избранном",
    favoritesTitle: "Избранные отели",
    favoritesSubtitle: "Отели, которые вы отметили сердечком в каталоге.",
    favoritesLoading: "Загрузка избранного…",
    favoritesEmpty:
      "В избранном пока пусто. Нажмите ♥ на карточке отеля в каталоге.",
    favoritesBrowse: "Открыть каталог",
    addFavorite: "В избранное",
    removeFavorite: "Убрать из избранного",
    loginForFavorite: "Войдите, чтобы сохранять отели в избранное",
  },
  bookings: {
    title: "Мои брони",
    subtitle: "Ваши бронирования — только вы видите эти заказы.",
    loading: "Загрузка броней…",
    empty: "У вас пока нет броней. Выберите отель в каталоге.",
    browse: "Перейти в каталог",
    guest: "Гость",
    email: "Email",
    total: "Итого",
    cancel: "Отменить",
    cancelConfirm: "Отменить это бронирование?",
    apiError: "Не удалось загрузить брони. Войдите снова или проверьте API.",
    listLabel: "Список ваших броней",
  },
  currency: " ₽",
};
